title: Urban Template
url: "https://baldoequeiroz.github.io"
baseurl: "/urban-jekyll-template"
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Baldo e Queiroz Advocacia

# Author details for the jekyll-seo-tag gem
author: 
  name: Baldo e Queiorz Advogados
  email: "advocacia@baldoequeiroz.com.br"
  twitter: baldoequeiroz # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Urban Template
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

collections:
  staff_members:
    output: true
  clients:
    output: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
